{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "name" : "categories",
  "children" : [ {
    "name" : "Product defects",
    "children" : [ {
      "name" : "cy.get(...).attachFile is not a function",
      "children" : [ {
        "name" : "File Upload",
        "uid" : "45a71f291ce1782c",
        "parentUid" : "2a97aebcd49345800cc84aefe89519fe",
        "status" : "failed",
        "time" : {
          "start" : 1671296353308,
          "stop" : 1671296363682,
          "duration" : 10374
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "2a97aebcd49345800cc84aefe89519fe"
    }, {
      "name" : "Timed out retrying after 4000ms: The command was expected to run against origin `https://opensource-demo.orangehrmlive.com` but the application is at origin `https://www.google.com`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://www.google.com` will likely fix this issue.\n\n`cy.origin('https://www.google.com', () => {`\n`  <commands targeting https://www.google.com go here>`\n`})`\n\nhttps://on.cypress.io/cy-visit-succeeded-but-commands-fail",
      "children" : [ {
        "name" : "Google Search",
        "uid" : "318d111e74cdb584",
        "parentUid" : "b7f885b0c817466eca61e62076195ee0",
        "status" : "failed",
        "time" : {
          "start" : 1671296461206,
          "stop" : 1671296475690,
          "duration" : 14484
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "b7f885b0c817466eca61e62076195ee0"
    } ],
    "uid" : "8fb3a91ba5aaf9de24cc8a92edc82b5d"
  } ]
}